[workers]
node1 ansible_host=localhost ansible_port=2221 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/ansible_key
node2 ansible_host=localhost ansible_port=2222 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/ansible_key
node3 ansible_host=localhost ansible_port=2223 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/ansible_key
